name: MFTSEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - pytorch-lightning
  - pytorch-forecasting
  - pandas
  - numpy
  - scikit-learn
  - tensorboard
  - pip
  - pip:
    - torch