name: MFTSEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - pytorch-lightning
  - pytorch-forecasting
  - pandas
  - numpy=1.26.4
  - scikit-learn
  - pip
  - tensorboard
  - sqlite
  - pip:
    - torch
    - optuna
    - statsmodels
    - optuna-integration