name: MFTSEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - pytorch-lightning
  - pytorch-forecasting
  - pandas
  - numpy
  - scikit-learn
  - tensorboard
  - protobuf=3.20.1
  - pip
  - pip:
    - torch