VAL_RATIO = 0.1
TEST_RATIO = 0.1
BATCH_SIZE = 32
SEQ_LENGTH = 1008
LF_LENGTH = 28
IF_LENGTH = 168
DELAY = 432
LR = 1e-4
JENA_PATH = '../data/jena_climate_2009_2016.csv'
MODEL_PATH = '../models/'
HISTORY_PATH = '../history/'

# Settings for the TFT Model
TFT_LR = 1e-3
HIDDEN_SIZE = 16
ATTENTION_HEAD_SIZE = 4
DROPOUT = 0.1
HIDDEN_CONTINUOUS_SIZE = 8
LOG_INTERVAL = 10
TFT_OPTIMIZER = 'Adam'
PATIENCE = 4
